apiVersion: v2
name: firehose-ethereum
description: A Helm chart for Kubernetes
type: application
version: 1.3.0
appVersion: geth-v1.16.5-fh3.0
keywords:
  - firehose
  - substreams
annotations:
  lookupName: "ghcr.io/streamingfast/go-ethereum"
