apiVersion: v2
name: substreams-tier-2
description: A Helm chart for deploying substreams-tier-2
type: application
version: 1.1.2
appVersion: v2.14.2
keywords:
  - substreams-tier-2
  - firehose-ethereum
annotations:
  lookupName: "ghcr.io/streamingfast/firehose-ethereum"
