{{- $values := $.Values.fullMode }}
{{- if and (eq .Values.mode "full") $values.components.reader.enabled }}
{{- $componentName := "reader" }}
{{- $componentLabel := include "firehose-ethereum.componentLabelFor" $componentName }}
{{- $secretName := printf "%s-firehose-jwt" .Release.Name }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $jwt := "" }}
{{- if $existingSecret }}
  {{- $jwt = index $existingSecret.data "jwt.hex" | b64dec }}
{{- else }}
  {{- $jwt = printf "%s%s" (uuidv4 | replace "-" "") (uuidv4 | replace "-" "") }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-firehose-jwt
  labels:
    {{- include "firehose-ethereum.labels" . | nindent 4 }}
    {{- $componentLabel | nindent 4 }}
type: Opaque
data:
  jwt.hex: {{ $jwt | b64enc }}
{{- end }}