apiVersion: v2
name: horcrux
description: A production-grade Helm chart for deploying Horcrux remote signer for Cosmos chains
type: application
version: 2.0.0
appVersion: "3.3.2"
keywords:
  - cosmos
  - horcrux
  - validator
  - remote-signer
  - blockchain
home: https://github.com/strangelove-ventures/horcrux
sources:
  - https://github.com/strangelove-ventures/horcrux
maintainers:
  - name: Horcrux Team
    url: https://github.com/strangelove-ventures/horcrux
icon: https://avatars.githubusercontent.com/u/87437622?s=200&v=4




