apiVersion: v2
name: firehose-core
description: A Helm chart for Kubernetes
type: application
version: 1.2.4
appVersion: v1.12.1
keywords:
  - firehose
  - substreams
annotations:
  lookupName: "ghcr.io/streamingfast/firehose-core"
