{{- if and (eq .Values.shards.method "externalSecret") .Values.shards.externalSecrets.enabled }}
{{- range $i := until (int .Values.replicaCount) }}
{{- $shardConfig := index $.Values.shards.externalSecrets.shardConfigs $i }}
{{- $shardId := int $shardConfig.shardId }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "horcrux.fullname" $ }}-shard-{{ $shardId }}
  namespace: {{ include "horcrux.namespace" $ }}
  labels:
    {{- include "horcrux.labels" $ | nindent 4 }}
    app.kubernetes.io/shard: "{{ $shardId }}"
spec:
  refreshInterval: {{ $.Values.shards.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.shards.externalSecrets.secretStoreRef.name }}
    kind: {{ $.Values.shards.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "horcrux.fullname" $ }}-shard-{{ $shardId }}
    creationPolicy: Owner
  data:
  - secretKey: {{ $.Values.chain.id }}_shard.json 
    remoteRef:
      key: {{ $shardConfig.providerShardKey | quote }}
  - secretKey: ecies_keys.json
    remoteRef:
      key: {{ $shardConfig.eciesKeysKey | quote }}
  - secretKey: {{ $.Values.chain.id }}_priv_validator_state.json
    remoteRef:
      key: {{ $shardConfig.validatorStateKey | quote }}
{{- end }}
{{- end }}

