{{- if .Values.service.headless.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "horcrux.serviceName" . }}
  namespace: {{ include "horcrux.namespace" . }}
  labels:
    {{- include "horcrux.labels" . | nindent 4 }}
  {{- with .Values.service.headless.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.headless.type }}
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "horcrux.selectorLabels" . | nindent 4 }}
  ports:
  - name: p2p
    port: {{ .Values.service.headless.p2pPort }}
    targetPort: p2p
    protocol: TCP
{{- end }}

