{{- if .Values.service.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "horcrux.metricsServiceName" . }}
  namespace: {{ include "horcrux.namespace" . }}
  labels:
    {{- include "horcrux.labels" . | nindent 4 }}
  {{- with .Values.service.metrics.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.metrics.type }}
  selector:
    {{- include "horcrux.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: {{ .Values.service.metrics.port }}
    targetPort: debug
    protocol: TCP
{{- end }}

